### ISSUE TITLE
Disable `unknown signature` warning for Killing Floor 1 packages.

### ISSUE THREAD

**Issue by Shtoyan** [UE-Explorer/UE-Explorer#30]
![image](https://user-images.githubusercontent.com/22412356/210520232-42122162-524e-4b65-af7a-99a85c9dd03b.png)

We all can blame 200IQ devs for changing the package signature without any need, but this warning is bane of my existence 😂 I use your app quite a lot, and this little window eats both time and some nerves each time it pops. Can you please add KF1 to exceptions and not show it?

**Comment by EliotVU** [comment]
Haha, sure! I think I'll best address this issue in the UE-Library by extending the auto-detection feature to recognize file signatures.
