### ISSUE TITLE
Feature request + ?bug

### ISSUE THREAD

**Issue by niko-kv** [UE-Explorer/UE-Explorer#32]
Hey!
I have a few things toward **UEE**:

1) [**FEATURE // HEX-viewer**] Inside the HEX-viewer it is really lack of `jump` (to certain offset) option. Yeah for small funtions/defaultprops it is not an issue, but I had examples when defaultprops were ~500kb and it is really hard work with searching inside the viewer (in that case I used 3rd party HEX-editor to be able to deal with defaultprop as a binary file).

2) [**FEATURE // HEX-viewer**] It would be really helpful to get possibility to copy any data in bottom part of the HEX-viewer (Size, PositionStartDEC, PositionOffestDEC, PositionHex).

3) [**FEATURE // HEX-viewer**] Inside the window of showing function's UnrealScript I suggest to add **click** or **hover** events. Click/hover on certain element of code will highlight it and will show it local tooltip with data of that element position/offset (HEX & DEC) inside the Buffer view. It will be opposite to what is currently UEE is showing inside the "View Buffer", when hover event make UEE to show this byte participation inside UnrealScript code.
Regarding of "Click", probably it would be cool to make UEE to push inside Copy/Paste buffer all info about clicked part of the code (dec + hex info).

**Example:**
![feature1_1](https://user-images.githubusercontent.com/59071887/215626797-79473e73-af35-4b3e-8513-7852773d9a15.jpg)

Especially such functionality will be very useful with working with **defaultproperties**. Because it is a real pain to work with massive defaultproperties and manually find their local offset via "View Buffer".

**Example:**
![feature1_1](https://user-images.githubusercontent.com/59071887/215621947-e9d08716-f67e-47b1-9ec5-c42263cd7e9e.jpg)

4) [?**BUG // HEX-viewer**] Inside the HEX-viewer mouse wheel is not cause any action (inside HEX bytes container).
IIRC that was working before. For now only helps using scrollbar. Maybe it is just only me.

Thanks!

**Comment by EliotVU** [comment]
>     1. [**FEATURE // HEX-viewer**] Inside HEX-viewer really lack of `jump` (to certain offset) option. Yeah for small funtions/defaultprops it is not an issue, but I had examples when defaultprops were ~500kb and it is really hard work with searching inside viewer (in that case I used 3rd party HEX-editor to be able deal with defaultprop as binary file).

Yeah, navigating defaultproperties is a pain in the *** for sure. This might be easy to implement too!

>     2. [**FEATURE // HEX-viewer**] Would be really helpful to get possibility to copy any data in bottom part of the HEX-viewer (Size, PositionStartDEC, PositionOffestDEC, PositionHex).

Good idea, I'll add a copy position command to the context menu.

>     3. [**FEATURE // HEX-viewer**] Inside window of showing function's UnrealScript I suggest to add **click** or **hover** events. Click/hover on certain element of code will highlight it and will showing it local tooltip with data of that element position/offset (HEX & DEC) inside Buffer view. It will be opposite to what is currently UEE is showing inside "View Buffer", I mean if click on certain byte UEE will show it UnrealScript representation.

This is being worked on (develop branch for 1.4 or 2.0), so far this works for the new "Listing" feature, which is much alike of that in Ghidra.

>     4. [?**BUG // HEX-viewer**] Inside HEX-viewer mouse wheel is not cause any action (inside HEX bytes container).
>        IIRC that was working before. For now only helps using scrollbar. Maybe it is just only me.

Yeah, last I tried but failed, I think this bug has been there for the entire existence of UE Explorer :)

**Comment by niko-kv** [comment]
> Yeah, navigating defaultproperties is a pain in the *** for sure. This might be easy to implement too!

Eliot, about the feature-1.
I'm trying to find something related in HexViewer of v1.4.1, but don't see sign of presence.
Just would like to know are there any plans to add this?
