### ISSUE TITLE
High DPI Scaling Issues: Distortion in UI Elements and Overlapping Text in Buffer View

### ISSUE THREAD

**Issue by Hox8** [UE-Explorer/UE-Explorer#33]
I've encountered distortion in several UI elements when running Unreal Engine Explorer on a high DPI display. Many of the distorted elements remain functional (such as the title bar and tabs), but the buffer view becomes largely unusable due to overlapping characters.

A temporary workaround I've found is to change the DPI scaling in Windows to 100%, launch Unreal Engine Explorer, and then revert the DPI scaling back to its previous value. This results in a blurry UI, but with no graphical distortion.

Attached are some images demonstrating said distortion.
<img width="1026" alt="UEE_DistortionTitleBar+Tabs" src="https://user-images.githubusercontent.com/125164507/233007534-f99220a7-a63e-49c5-8584-6ac6591d7103.PNG">
<img width="567" alt="UEE_Distortion_BufferView" src="https://user-images.githubusercontent.com/125164507/233007589-955e1c56-e987-4c6f-813e-81f44cb8b683.PNG">

**Comment by EliotVU** [comment]
Thanks!

This might be fixable: https://learn.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8 

I'll see if I can release a hotfix if the above solution does indeed solve the issue.

**Comment by pingwindev** [comment]
As a convenient workaround, instead of switching the global DPI scaling you can also override it specifically for the UE Explorer executable. :)

![override-hDPI-scaling](https://github.com/UE-Explorer/UE-Explorer/assets/2534873/5bc3b717-238e-4231-88fd-f503b505143e)

**Comment by EliotVU** [comment]
@artism90 Good tip!

I've partially rewritten some of the rendering code to take the font's width into account, this will be included with version 1.3.2.

DPI scaling at 175%:
![image](https://github.com/UE-Explorer/UE-Explorer/assets/808593/76846065-849c-4cc8-91bb-1ceb716584be)

The tabs and columns are still misaligned but this is quite an extreme DPI, it's alright at 150%.
