### ISSUE TITLE
Hawken package unknown signature

### ISSUE THREAD

**Issue by Tom-Neverwinter** [UE-Explorer/UE-Explorer#35]
Trying to figure out the Hawken pax client it is impossible to open critical items. 

https://drive.google.com/file/d/1bXj0wxjNct_kvndWWufxPqKWVnHdP2zV/view?usp=sharing

**Comment by EliotVU** [comment]
Thanks!

It appears that version 860/002 is compatible, but UE Explorer does not auto-detect that version as a Hawken package; setting the version manually however does not fix the issue (strange!)

**Comment by Tom-Neverwinter** [comment]
any assistance with this will make a lot of mech pilots very happy. we are trying desperately to resurrect our dead game. 
we have generated an sdk from files its so desperate
