### ISSUE TITLE
Error when opening Splinter Cell 1 package

### ISSUE THREAD

**Issue by mirh** [UE-Explorer/UE-Explorer#37]
`Engine.u` specifically. 
```
Thrown by:LoadPackage
   in UEExplorer.UI.Tabs.UC_PackageExplorer.LoadPackage()
   in UEExplorer.UI.ProgramForm.LoadFile(String fileName)System.ArgumentOutOfRangeException: non-negative number required
Parameter name: capacity
   in System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   in System.Collections.Generic.List`1..ctor(Int32 capacity)
   in UELib.UnrealStreamImplementations.ReadArray[T](IUnrealStream stream, UArray`1& array, Int32 count)
   in UELib.UnrealPackage.Deserialize(UPackageStream stream)
   in UELib.UnrealLoader.LoadPackage(String packagePath, FileAccess fileAccess)
   in UEExplorer.UI.Tabs.UC_PackageExplorer.LoadPackage()
```

**Comment by EliotVU** [comment]
Unfortunately Splinter Cell 1 is not yet supported, see https://github.com/EliotVU/Unreal-Library?tab=readme-ov-file#compatible-games for a list of compatible games.

**Comment by mirh** [comment]
Then take this as a feature request as opposed to a wontfix¿

**Comment by Shtoyan** [comment]
Heh, I tried to do the same thing when I was playing few months ago.

**Comment by EliotVU** [comment]
Sure, but this should be moved over to the UELib repository instead.

Made some progress, the changes to the package format are rather simple:
![image](https://github.com/UE-Explorer/UE-Explorer/assets/808593/6d819b78-c859-41b5-bb62-1c241af347b9)

**Comment by Shtoyan** [comment]
Clean looking GUI, btw.
