### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by mdadduzio** [UE-Explorer/UE-Explorer#42]
There are probably some missing files in the last commit 40529c8 to solve the scrolling issue of the HexViewer.
At first the build fails because of a missing  HexViewerPanel.resx and then (when whichever icon is added to replace such missing one): 

2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.CSharp.CurrentVersion.targets(129,9): warning MSB3884: Could not find rule set file "AnalyzeRules.ruleset".
1>  Eliot.UELib.Demo -> D:\UE-Explorer\UE-Explorer\Eliot.UELib.Demo\bin\Debug\Eliot.UELib.Demo.exe
2>CSC : error CS2001: Source file 'D:\UE-Explorer\UE-Explorer\UE Explorer\UI\Forms\HexViewerPanel.Designer.cs' could not be found.

Please check all (new/modified) files have been staged and committed.
TIA

**Comment by EliotVU** [comment]
Thanks for bringing this up!

**Comment by mdadduzio** [comment]
Works like charm!
Thank you for so prompt fix and thanks for such great project :-)
