### ISSUE TITLE
HEX-viewer & Edit Cell

### ISSUE THREAD

**Issue by niko-kv** [UE-Explorer/UE-Explorer#43]
Hi. Regarding of HEX-viewer:
In v1.3.2 seems I can't edit any byte-cell anymore. I pick "Edit Cell" in context menu, or just using double mouse click - It is mark cell with black and after pressing keys (0-9, a-f, A-F) not make any effect.
In v1.3.0 (I just checked) HEX-viewer can edit any byte-cell without problems.

P.S.: In my tests I used same UE-file.

**Comment by EliotVU** [comment]
Thanks, fix incoming with 1.3.3 :)
