### ISSUE TITLE
"Array type was not detected."

### ISSUE THREAD

**Issue by niko-kv** [UE-Explorer/UE-Explorer#44]
Hi, again :)

I noticed that sinse 1.3.* versions, some UE-files, which earlier shown "/* Array type was not detected. */", now seems better and more properly handle the detection and parsing of Arrays/Objects.

But still, there are some UE-files, which are still show such messages. Here is an example of such file. There is property "B_Boss_AttackSets.DefaultAttackSet_Center" inside, and UEE v1.3.2 parse this partition like this:
```
begin object name=DefaultAttackSet_Center class=SwordBossAttackSet
    AttackSets=/* Array type was not detected. */
    AttackProgression=/* Array type was not detected. */
object end
```
As you see on picrel such array is not empty, there is data exists. So is it possible to make this structure parseable?
Just in case if you needed, mentioned UE-file is attached to the post.
Thanks!

[file.zip](https://github.com/UE-Explorer/UE-Explorer/files/14657463/file.zip)

![example](https://github.com/UE-Explorer/UE-Explorer/assets/59071887/42c2f77c-fb86-4ecc-9475-721743f8361b)

**Comment by EliotVU** [comment]
See https://github.com/UE-Explorer/UE-Explorer/blob/UE-Explorer/FAQ.md

I can't pre-define these in particular because they are too game-specific. Once UELib is capable of properly linking packages(in v2.0) this will be automated.

**Comment by niko-kv** [comment]
Oh, I see. Partially I had similar assumptions, but I decided to make sure.
Thanks for clarification :)
