### ISSUE TITLE
(Feature request) Recent history entries

### ISSUE THREAD

**Issue by niko-kv** [UE-Explorer/UE-Explorer#47]
Hey!

I suggest it would be nice to add small improvement for the existing "←" & "→" history buttons. For example, add a history button that will display a modal window (or perhaps make it as a context menu) with list of previously visited classes/objects (or their methods/props). Regarding of max history entries, let's say 20-30 places.

Clicking on specific history entry will instantly take user to that place.

**Comment by EliotVU** [comment]
That's a great idea for the next major release. The current main build is still running on an ancient code base, it wouldn't make much sense to add new features to this old code.
