### ISSUE TITLE
(Error) Deserialization failed by exception v1.4.1.0

### ISSUE THREAD

**Issue by niko-kv** [UE-Explorer/UE-Explorer#53]
I tried a few different UE-files (in different games, which worked before), but now all show this:
(also same files openning much longer, probably of the errors)

![err](https://github.com/UE-Explorer/UE-Explorer/assets/59071887/2eb295cb-8a5e-497f-9cdc-6e3ca748095d)

**Comment by Hox8** [comment]
The issue seems to lie within the `IsConsoleCooked` method (UELib) assuming a `CookerPlatform` value of `Undetermined` is a PC platform. Infinity Blade is an example where this is not the case. Here's a quick fix which allows serialization for iOS Infinity Blade scripts. I haven't tested this on other titles.

from:
```cs
        public bool IsConsoleCooked()
        {
            return Summary.PackageFlags.HasFlag(PackageFlag.Cooked)
                   && CookerPlatform == BuildPlatform.Console;
        }
```

to:
```cs
        public bool IsConsoleCooked()
        {
            return Summary.PackageFlags.HasFlag(PackageFlag.Cooked)
                   && CookerPlatform != BuildPlatform.PC;
        }
```

**Comment by EliotVU** [comment]
:/ I'm unable to re-produce this issue, tested on Engine.u from Infinity Blade 788/001

**Comment by niko-kv** [comment]
Ah, it is pity. Well, please let me bring a bit more details:

**Infinity Blade 1** as 788/001 - deserialization goes without issues
~ No matter which **Console** or **PC** setting in use

**Infinity Blade 2** as 864/001 - goes with deserialization errors
~ All working in v1.3.5 (and versions below), with condition that we are set **Console**, instead of **PC** 
~ In v1.3.5 (and versions below) with picking "PC", deserialization is not happening, but also there is no errors and all functions shown as `function();`. Picking "Console" was a small trick to make UEE to show IB2/3 game code. All who working with IB2/3 modding are use to it.

**Infinity Blade 3** as 868/000 - goes with deserialization errors
~ Same as was described for IB2 above

~ ~ ~
**(!!)** Most funny, I just tried a bit silly trick:
1) I picked a few random files from IB2 and IB3.
2) In their headers I changed bytes which are corresponding for the **build** & **lic. version** parameters, from `60 03 01 00`(=864/1) or `64 03 00 00`(=868/0) to `14 03 01 00`(=788/1).
2) Then I opended the file in UEE v1.4.1.0 and all deserialization errors are gone, deserialization is working.

**Comment by EliotVU** [comment]
Thanks for providing that information!

I don't own a copy of Infinity Blade 2 with that package version.
My copy (842/001) seems to work just fine as well, I believe the newer version is not auto-detected in UELib, so that should be an easy fix.

Neither own IB3, and Injustice Mobile. I believe the issue here is https://github.com/EliotVU/Unreal-Library/pull/74

**Comment by niko-kv** [comment]
_[Sorry accidentaly deleted my previous post lol]_

Ah, it is pity. Well, please let me bring a bit more details:

**Infinity Blade 1** as 788/001 - deserialization is working (build is `InfinityBlade`)
~ No matter which **Console** or **PC** setting in use

**Infinity Blade 2** as 864/001 - goes with deserialization errors (build is `Unknown`)
~ In v1.3.5 (and versions below) deserialization is working, with a condition that we are using setting **Console**, instead of **PC**. In case of picking "PC", deserialization is not happening, but also there is no errors and all functions shown as `function();`. Inside the tab "Export" > "Tables" all that isn't contains "Default__*" are marking with green, not red.
Picking "Console" was a small trick to make UEE to show IB2/3 game code. All who working with IB2/3 modding are use to it.

**Infinity Blade 3** as 868/000 - goes with deserialization errors (build is `Unknown`)
~ Same as it was described for IB2 above

**Injustice Mobile** as 868/008 - goes with deserialization errors (build is `Unknown`)
~ Same as it was described for IB2 above

~ ~ ~

**(!)** Most funny, I just tried a bit silly trick:
1) I picked a few random files from the IB2 and IB3.
2) In their headers I manually changed bytes which are corresponding for the **build** & **lic. version** from `60 03 01 00`(=864/1) or `64 03 00 00`(=868/0) to `14 03 01 00`(=788/1).
3) Then I opended these files in UEE v1.4.1.0. UEE shows the build as `InfinityBlade`. Deserialization errors are gone and deserialization is working. Even don't matter If I use "PC" or "Console" setting.

~ ~ ~

I hope all this will helps. Thanks for attention to this issue!

**Comment by niko-kv** [comment]
Eliot, please check your contact@ email I sent you something, just as an additionion to the post.

**Comment by EliotVU** [comment]
Thanks! I have updated UELib to auto-detect all the listed builds.
