### ISSUE TITLE
Borderlands / Borderlands GOTY

### ISSUE THREAD

**Issue by sunbeam906** [UE-Explorer/UE-Explorer#55]
Hello.

Tested latest UE Explorer 1.4.1 with **Borderlands** or **Borderlands GOTY**. I haven't read of any support for these games, just Borderlands 2, so maybe you can have a look into it? Below are the unpacked **.u** files from both builds.

[BL.zip](https://github.com/UE-Explorer/UE-Explorer/files/15109195/BL.zip)

Test scenarios:

- with 1.3.0 I at least get error messages or unfinished "Linking Objects" operations with errors (the list of objects does become available, but trying to expand any tree leads to app freeze)
- with 1.4.1 it gets stuck at "Deserializing Objects" and after a long while it throws a .NET error
- tested only with GOTY Engine.u as the other one doesn't work at all

![image](https://github.com/UE-Explorer/UE-Explorer/assets/148178/bd220744-ed7a-4dd8-82df-c50c7eadd1bb)

- clicking OK on the above and inspecting the tree shows a super-partial listing of what could be deserialized:

![image](https://github.com/UE-Explorer/UE-Explorer/assets/148178/40b3e142-5f5e-4e7b-b1a1-43d0f8333310)

**Comment by EliotVU** [comment]
Thanks for the files. Seems like Borderlands 1's support has regressed, and is missing full support (not all format changes are recognized).

**Comment by sunbeam906** [comment]
Seeing your message, I've decided to take the old versions for a spin. Here are my tests:

- 1.2.7.1:
  - Borderlands (x86): does not error at all on Engine.u and WillowGame.u
  - Borderlands (x86): missing every UFunction from the tree hierarchy (checked GameViewportClient, CheatManager, etc.)
  - BorderlandsGOTY (x64): cannot load at all Engine.u and WillowGame.u
  - BorderlandsGOTY (x64): stuck at "Deserializing Objects"

![image](https://github.com/UE-Explorer/UE-Explorer/assets/148178/40dd2e6c-4a46-4539-a4d3-f7f9773818fc)

- 1.3.0.0:
  - Borderlands (x86): errors with the Exception Occurred "Unable to read beyond the end of the stream." message.
  - BorderlandsGOTY (x64): stuck at "Deserializing Objects", but progression bar goes further than 1.2.7.1
  - BorderlandsGOTY (x64): errors moments later with Exception Occurred "Event:Linking Objects" message.
  - in either build, attempting to expand a tree node after clicking away the errors will result in a freeze of the GUI

All the way up to 1.4.1 (inclusively) there are either exceptions or freezes.

Seems that only 1.2.7.1 and with x86 .u files does something, even if incomplete. Missing **UFunctions** from the listing is a concern, don't know if you've been aware of it since 2015...

Thanks and looking forward to a hotfix!

BR,
Sun

**Comment by EliotVU** [comment]
Thanks :) I'm looking into it.

**Comment by EliotVU** [comment]
Fixed :) Will be released with the next update or possible hotfix.

**Comment by sunbeam906** [comment]
Great to hear! I'm also working on the game, been a while since I touched it. That's how I got to discover UE Explorer was a bit off. Looking forward to the release; no rush.
