### ISSUE TITLE
(UI Suggestion) Opened files tooltip with their path

### ISSUE THREAD

**Issue by niko-kv** [UE-Explorer/UE-Explorer#57]
I have examples, when simultaneously can be opened a few copies of file (with same names), but which lay in different places. So it is hard to tell which file is where from first sight. To find out their locations I need to go check option **File** > **Recent Files** and see the order.

My small UI suggestion is to add hover-tooltip (with file's path), when user is set the mouse above certain file tab. By that will be easy to recognize opened files with similar names.

P.S.: Also it would be cool to get hover-tooltop for every tab inside tabs vertical list (I mean arrow-button near button X)

![example](https://github.com/UE-Explorer/UE-Explorer/assets/59071887/a932b335-b0b9-4d76-8dfc-36b30cb9c66e)

**Comment by EliotVU** [comment]
Done!
