### ISSUE TITLE
v1.3.1.0 - cannot check for updates when discarded automatic checks

### ISSUE THREAD

**Issue by guitronimo** [UE-Explorer/UE-Explorer#60]
Hi, 

thanks for this wonderful tool. I just have realized this github. 
Not sure if this applies for newer versions aswell, i report it anyway. 

When discarding the automatic update check at the beginning, i am not able to open
Help -> Check for Updates

Windows 11 latest

Cheers

**Comment by EliotVU** [comment]
Glad you find it useful!

Will see if I can verify this, also probably an issue with the auto updater vendor.

**Comment by guitronimo** [comment]
I just realized that the "Check for updates" entry appears to do nothing, even in the new version. 1.4.

Not too big of an issue though and certainly doesnt have any priority.
