### ISSUE TITLE
Error unpacking BIOC_Base,u after decompressing with Gildor's Decompressor

### ISSUE THREAD

**Issue by PentaChess413** [UE-Explorer/UE-Explorer#62]
It states the package is compressed despite having gone to the decompressor and keeping the same size. The package is from ME1 (Mass Effect)

**Comment by EliotVU** [comment]
Mass Effect support is not yet integrated in the current release of UELib (which powers UE Explorer)

FYI: Mass Effect support does exist in a local branch but has not been pushed to the main branch as of yet.
