### ISSUE TITLE
(Suggestion) Show indexes of all Enums

### ISSUE THREAD

**Issue by niko-kv** [UE-Explorer/UE-Explorer#64]
Hey!
It'd be nice and very helpful to see UEE giving some enchanced view of all parsed enums (by default).
By saying **enhanced** I suggesting to add extra comments with indexes as DEC/HEX.

For example:
```
enum SomePersonState
{
	SPS__Sleeping, // 0 (0x00)
	SPS__Eating, // 1 (0x01)
	SPS__Thinking, // 2 (0x02)
	...
	SPS__Walking, // 12 (0x0C)
	SPS__Running, // 13 (0x0D)
	SPS__Swimming, // 14 (0x0E)
	SPS__Jumping, // 15 (0x0F)
	...
	SPS__Dead, // 35 (0x23)
	SPS__MAX // 36 (0x24)
}
```

**Comment by EliotVU** [comment]
That would be a nice addition indeed, but I don't think we should add the hex-decimal format.

**Comment by EliotVU** [comment]
![image](https://github.com/user-attachments/assets/5f8822eb-00e6-494c-9893-6d3f0068f99d)

Thoughts?

**Comment by EliotVU** [comment]
Eventually we should have hover tooltips that will display the value as desired (The underlying decompiling system has been re-written (partially) to write using an AST of nodes and output tokens instead, so that the editor can track where the output originated from)

**Comment by niko-kv** [comment]
Looks great :) Thanks!
