### ISSUE TITLE
No error crash opening borderlands 1 '.u' files

### ISSUE THREAD

**Issue by RedxYeti** [UE-Explorer/UE-Explorer#65]
trying to open a borderlands 1 .u file will send the program into not responding.

I've uploaded a cooked file here if you want to try yourself.
https://github.com/RedxYeti/Yeti-BL2-SDK-Mods/blob/main/WillowGame.u

Borderlands 1 is ue3

**Comment by EliotVU** [comment]
Duplicate of #55 Thanks though.
