### ISSUE TITLE
Crash on 1.4.2 start

### ISSUE THREAD

**Issue by mirh** [UE-Explorer/UE-Explorer#66]
Requested value 'Ctrl' was not found
```
Thrown by:TryParseEnum
   in System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   in System.Windows.Forms.KeysConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   in System.Resources.Extensions.DeserializingResourceReader.DeserializeObject(Int32 typeIndex)
   in System.Resources.Extensions.DeserializingResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   in System.Resources.Extensions.DeserializingResourceReader.LoadObject(Int32 pos)
   in System.Resources.Extensions.DeserializingResourceReader.ResourceEnumerator.get_Entry()
   in System.Resources.Extensions.DeserializingResourceReader.ResourceEnumerator.get_Current()
   in System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   in System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   in System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   in System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   in UEExplorer.UI.ProgramForm.InitializeComponent()
   in UEExplorer.UI.ProgramForm..ctor()
   in UEExplorer.Program.SingleInstanceApplication.OnCreateMainForm()
   in Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   in Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
```

**Comment by SparkleArts** [comment]
I have the same issue.

**Comment by EliotVU** [comment]
:/ Perhaps this was instigated by commit c52cded8 ?

**Comment by RenBIT** [comment]
У меня возникла похожая проблема, но, кажется, я нашел решение, и мой проект успешно скомпилировался!

**Как я решил проблему в Visual Studio:**

1. Перейдите в меню **Правка** -> **Найти и заменить** -> **Заменить в файлах**.
2. В первое текстовое поле введите **"Ctrl"**, а во второе  **"Control"** без кавычек.
3. Нажмите кнопку **Заменить все**.

**Comment by mirh** [comment]
The problem is all the keyboard shortcuts like this placed around the program. 

https://github.com/UE-Explorer/UE-Explorer/blob/450cf37a68ecf60b5a907eddd26f63b323cbbe52/UE%20Explorer/UI/Main/ProgramForm.resx#L228-L230

In order to load packages you also have to rename the ones in:
https://github.com/UE-Explorer/UE-Explorer/blob/UE-Explorer/UE%20Explorer/UI/Tabs/UC_PackageExplorer.resx
https://github.com/UE-Explorer/UE-Explorer/blob/UE-Explorer/UE%20Explorer/UI/Forms/HexViewerForm.resx
Afterwards c52cded8bb31afa8548274acf606a1e23e39d23a doesn't seem to do anything.

**Comment by EliotVU** [comment]
Thanks! Appears to be a bug with the .Net Framework where Ctrl is being localized to the platform's? language.

**Comment by mirh** [comment]
I don't think you needed to also replace its name in the documentation.
