### ISSUE TITLE
Deserialization no longer working on Borderlands 2, Borderlands: The Pre-Sequel, or Tiny Tina's Assault on Dragon Keep: A Wonderlands One-shot Adventure UPK files

### ISSUE THREAD

**Issue by przemo20** [UE-Explorer/UE-Explorer#67]
The last UE Explorer version that this was working fine was [1.3.5](https://github.com/UE-Explorer/UE-Explorer/releases/tag/1.3.5).

### Example steps to reproduce
1. Download and extract this .zip file with decompressed Startup.upk files: https://mega.nz/file/KoRgVTiL#8PaOzwvdGURAgfHGIFN1mA6bRyoG0B74Hmb8DiBReJM
2. Open the Startup.upk file for Borderlands 2 in UE Explorer
3. Switch to the Objects tab, scroll down to `GD_Weap_Pistol`, expand it, then expand Name → Title and click on `Title__Unique_Dahlminator`

#### Now (version 1.4.3):
![obraz](https://github.com/user-attachments/assets/168e9d64-572d-4394-a238-7a7f68829b08)

(when you click on “View Exception”)
![obraz](https://github.com/user-attachments/assets/55c8a4cb-9e55-4a84-937b-24178cbc99c5)

#### Before (version 1.3.5):
![obraz](https://github.com/user-attachments/assets/6dfae70e-1fa4-4daa-817c-7e17489cd259)

**Comment by EliotVU** [comment]
Thanks, looks like algorithm to detect if an unknown class type might potentially be a `UComponent` derivative is failing here. I have a work-around ready which will abort the detection if the algorithm triggers an exception.
